### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by RomeshA**
This PR adds migration. It's essentially uses the same approach from Optima HIV where migration is performed at the project level by chaining migration functions. The implementation is slightly simplified using decorators and also no longer requires `None` migrations solely due to version changes. The basic strategy is that `migration.py` stores a list of `Migrations` which are registered using the `@migration` decorator. The `migrate` function iterates over them in version order (using the built-in `distutils.version.LooseVersion` to sort the version strings correctly/semantically). The migration decorator takes in the versions, description, and optionally date. In practice, it looks like:

```
@migration('1.0.5', '1.0.6','Migration 1')
def foo(proj):
    <do stuff>
    return proj

@migration('1.0.7', '1.0.8','Migration 2','2019-01-01')
def bar(proj):
    <do stuff>
    return proj
```

Note that migrations will be run in version order as long as the project version is less than the original version. Thus in the example above, it will run Migration 1 followed by Migration 2 even though there is no explicit migration for 1.0.6->1.0.7 (in the previous system, tthis is equivalent to the code assuming that any unspecified jump in version number has a 'None' migration). Thus when implementing a change that requires a migration, simply specify the original version as whatever is currently in the repository, and then increment the version number as required.

Project migration is called automatically by `Project.load()`. That function also checks that the pickled file actually contained a `Project` object. Projects should almost always be loaded using `P = Project.load(fname)` rather than using `P = sc.loadobj(fname)` directly.

As a test, this PR also simplifies the `ParameterSet` by flattening the parameter dict

### CODE REVIEW

**Comment by RomeshA** [comment]
[Migrations](https://trello.com/c/BvfjM4zW/142-migrations)

**Comment by RomeshA** [comment]
[Do parsets need to differentiate between par types?](https://trello.com/c/JzsmqjRc/256-do-parsets-need-to-differentiate-between-par-types)

**Comment by RomeshA** [comment]
Ah @cliffckerr my understanding is that the HIV-style approach is to use project-level migration to migrate all objects e.g. if something in the Result changes, it's updated from within a project. But in the FE, the Results are stored separately. How does Optima HIV handle result migrations?

**Comment by RomeshA** [comment]
[Make a proper plan for migrations](https://trello.com/c/PW5B4fzA/693-make-a-proper-plan-for-migrations)

**Comment by robynstuart** [comment]
@RomeshA since I've reviewed this, I'm going to merge it now - I know it's been superseded but i can merge the subsequent ones separately

**Pull request merged**
