### PR TITLE
Uncertainty

### PR DESCRIPTION
**Pull request by RomeshA**
This PR introduces a mechanism for sampling from parsets and progsets with uncertainty, as well as functions for managing uncertainty results and plotting uncertainties. In some ways it's still a work in progress, but the PR also incorporates other changes for tidying and documentation and it's growing in size - uncertainty is just about feature-complete now and we've reviewed the feature set in the group call, so my inclination would be to merge it at this point and then continue working on it from there - particularly because the parts that affect existing other code (like removing the `sample` argument from some methods) are quite well developed now, and the remaining tidying etc. is on standalone functions that aren't used by anything else yet. Otherwise, I'm concerned that uncertainty will be too big a feature to merge in one go, if we delay merging

### CODE REVIEW

**Comment by RomeshA** [comment]
[Summary method for cascade results](https://trello.com/c/WSWOHDd7/739-summary-method-for-cascade-results)

**Comment by RomeshA** [comment]
[Record coverage etc?](https://trello.com/c/fHQIAWmx/702-record-coverage-etc)

**Comment by RomeshA** [comment]
[Uncertainty](https://trello.com/c/ImvA59Om/119-uncertainty)

**Comment by robynstuart** [comment]
@RomeshA this all looks great - thanks for giving me the chance to experiment with it! Merging now so we can move onto the Next Big Things 👍

**Pull request merged**
