### PR TITLE
New method for reading version number

### PR DESCRIPTION
**Pull request by cliffckerr**
Small change to read the version number a la Scipy

### CODE REVIEW

**Comment by RomeshA** [comment]
Looks like importing `sciris` doesn't work inside `runpy` during the packaging process unfortunately (https://dev.azure.com/AtomicaTeam/Atomica/_build/results?buildId=434)

**Comment by RomeshA** [comment]
However, let's keep this PR open, in `mnch_extensions` it no longer imports sciris, so it might work with that change - probably easiest to revisit once that branch is merged

**Comment by ckerr-IDM** [comment]
@RomeshA As one possible solution, I put the Sciris import in a simple try-catch

**Comment by RomeshA** [comment]
Looks like the try-catch is still going to be needed, so overall it just feels like adds some awkward complexity without actually providing a functional improvement? What will using `runpy` add aside from being what `scipy` does?

**Pull request merged**
